### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by Brave-peng** [raphaelmemmesheimer/skeleton-dml#2]
Hello, thank  for your excellent wook!
And, when I use this code, I find some question:
1. I can't find the file ”requirement.txt“
2. I can't find the config file of scheduler

Could you supplement these files?
Looking forward to your reply!

**Comment by raphaelmemmesheimer** [comment]
Hey @Brave-peng,

sorry for the late answer. I just added the `requirements.txt`. I didn't use a scheduler for the paper, therefore there is no config.
