### ISSUE TITLE
 best accuracy and loss are not improved

### ISSUE THREAD

**Issue by yanghhx** [raphaelmemmesheimer/skeleton-dml#3]
I have trained the network 100 epoch, but the best accuracy and the loss are not improved. Could you tell me how to solve it?

**Comment by raphaelmemmesheimer** [comment]
Hey, I don't get you completely. There might be an intermediate epoch that results in a higher accuracy and a lower loss. However, I decided  to report the results for the final epoch.

Or doesn't the approach train at all? Can you post a log and a screenshot of the tensorboard output?

**Comment by yanghhx** [comment]
I have solved the problem. Thanks for your reply.
















At 2021-10-26 14:08:11, "Raphael Memmesheimer" ***@***.***> wrote:

Hey, I don't get you completely. There might be an intermediate epoch that results in a higher accuracy and a lower loss. However, I decided to report the results for the final epoch.

Or doesn't you approach train at all? Can you post a log and a screenshot of the tensorboard output?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanghhx** [comment]
Dear Doctor,
      I have read your two papers and related codes,Skeleton-DML: Deep Metric Learning for Skeleton-Based One-Shot Action Recognition and SL-DML: Signal Level Deep Metric Learning for Multimodal One-Shot Action Recognition. I have found the codes of them are very similar. I'm very interested in one-shot acition recognition based on skeleton and your works.Could you please tell me the difference? I'm very grateful if you reply to me.
















At 2021-10-30 16:28:10, "Raphael Memmesheimer" ***@***.***> wrote:

Closed #3.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by raphaelmemmesheimer** [comment]
You are right, the papers follow a similar approach with a different focus. *SL-DML* aims at generalizing across different modalities (inertial, skeleton, inter-modal) and proposes one-shot action recognition by employing metric learning. *Skeleton-DML* actually builds on the SL-DML idea but focuses on improving for skeleton-based action recognition with a much more in-depth ablation study on skeleton-data using different skeleton-based representations (also a new representation is suggested, that we found to perform better in our experiments). We actually also compare against *SL-DML* in the Skeleton-DML paper. In that case just the representation differs.  

The main differences are in the representation and the mining of the samples.

SL-DML representation

![sl-dml_S001C001P001R001A007 skeleton](https://user-images.githubusercontent.com/1682186/140951853-55f61633-db20-4869-86c3-3188bc090e1f.png)


Skeleton-DML representation

![skeleton_dml_S001C001P001R001A007 skeleton](https://user-images.githubusercontent.com/1682186/140951803-8d700ac6-cd82-4671-b5d1-0c397fdb5a5a.png)

Hope this helps. If you have further questions, I'm happy to answer them.

**Comment by yanghhx** [comment]
Thanks for your reply. I think I need to study more deeply.













At 2021-11-09 23:24:02, "Raphael Memmesheimer" ***@***.***> wrote:

You are right, the papers follow a similar approach with a different focus. SL-DML aims at generalizing across different modalities (inertial, skeleton, inter-modal) and proposes one-shot action recognition by employing metric learning. Skeleton-DML actually builds on the SL-DML idea but focuses on improving for skeleton-based action recognition with a much more in-depth ablation study on skeleton-data using different skeleton-based representations (also a new representation is suggested, that we found to perform better in our experiments). We actually also compare against SL-DML in the Skeleton-DML paper. In that case just the representation differs.

The main differences are in the representation and the mining of the samples.

SL-DML representation

Skeleton-DML representation

Hope this helps. If you have further questions, I'm happy to answer them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
