### ISSUE TITLE
skeleton data of  NTU 120 

### ISSUE THREAD

**Issue by yanghhx** [raphaelmemmesheimer/skeleton-dml#4]
I'd like to know why the skeleton data of NTU 120 in your work are the series pictures rather than the skeleton data,such as the coordinate data. Are the pictures feature vectors? How do you get them?

**Comment by raphaelmemmesheimer** [comment]
The data for skeleton-dml is constructed like described in the [paper](https://arxiv.org/pdf/2012.13823.pdf) (Figure 3 and 4). The simplest way to construct the data like this would be using the numpy reshape function with (-1,-1,3) as arguments.

**Comment by yanghhx** [comment]
Umm, I am sorry that I am still confused how the skeleton is related to the image representation. Could you please offer the related code?
















At 2021-11-09 23:09:52, "Raphael Memmesheimer" ***@***.***> wrote:

The data for skeleton-dml is constructed like described in the paper (Figure 3 and 4). The simplest way to construct the data like this would be using the numpy reshape function with (-1,-1,3) as arguments.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanghhx** [comment]
I have another question. When I set the bachsize to 16, the last iteration comes to error and remind me that the dimension is wrong.







At 2021-11-09 23:09:52, "Raphael Memmesheimer" ***@***.***> wrote:

The data for skeleton-dml is constructed like described in the paper (Figure 3 and 4). The simplest way to construct the data like this would be using the numpy reshape function with (-1,-1,3) as arguments.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanghhx** [comment]
Dear author:
       I am sorry to trouble you but I'd like to know why your dataset is not "one-shot" because it is the whole NTU 120 datasets. However, your work is "one shot action recognition", so can you tell me the reason?













At 2021-11-09 23:09:52, "Raphael Memmesheimer" ***@***.***> wrote:

The data for skeleton-dml is constructed like described in the paper (Figure 3 and 4). The simplest way to construct the data like this would be using the numpy reshape function with (-1,-1,3) as arguments.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by raphaelmemmesheimer** [comment]
> Umm, I am sorry that I am still confused how the skeleton is related to the image representation. Could you please offer the related code?

I'll try to give a short example on the representation generation soon.



> I have another question. When I set the bachsize to 16, the last iteration comes to error and remind me that the dimension is wrong.

Not sure what is happening there. Usually during training, it should randomly sample the amount of batch_size samples and because of the shuffling I'm quite sure that it should always fill up to the amount of samples. 



> I am sorry to trouble you but I'd like to know why your dataset is not "one-shot" because it is the whole NTU 120 datasets. However, your work is "one shot action recognition", so can you tell me the reason?

I suggest you to reread the paper and the NTU 120 paper carefully (The one-shot protocol is presented in a later section "One-Shot Recognition on NTU RGB+D 120"). In the paper we follow the one-shot action recognition protocol which is also described in the NTU 120 datset. Loosely spoken, you train a model on a set of up to 100 known classes and use 20 classes with one reference sample from each that have not seen during the training process for experiments. Initially, this might be a bit more tricky to understand, as  the problem is not framed in a supervised classification setting.

**Comment by raphaelmemmesheimer** [comment]
To elaborate on the One-shot Protocol, here is a simple generic sample:

Let's say during training, you can train your model on the following actions: 

* jumping
* running
* walking
* brushing teeth

at test time, in contrast, the following classes are contained with one reference sequence per class:

* falling
* walking
* drinking

**Comment by yanghhx** [comment]
Thank you very much. I've got it.










在 2021-12-13 18:22:41，"Raphael Memmesheimer" ***@***.***> 写道：

To elaborate on the One-shot Protocol, here is a simple generic sample:

Let's say during training, you can train your model on the following actions:

jumping
running
walking
brushing teeth

at test time, in contrast, the following classes are contained with one reference sequence per class:

falling
walking
drinking

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RCpengnan** [comment]
> I am still confused how the skeleton is related to the image representation. Could you please offer the related code?

 I am also confused how the skeleton is related to the image representation. Could you please offer the related code?Thank you

**Comment by raphaelmemmesheimer** [comment]
@RCpengnan i just added a simple example in the `representation` subfolder.
