### ISSUE TITLE
NameError: name 'dfg' is not defined

### ISSUE THREAD

**Issue by RCpengnan** [raphaelmemmesheimer/skeleton-dml#5]
Hello,I have two questions.
1.I am also confused how the skeleton is related to the image representation. Could you please offer the related code?
2. Could you tell me where the  'dfg' in train,py
Thank you.

**Comment by raphaelmemmesheimer** [comment]
> 1.I am also confused how the skeleton is related to the image representation. Could you please offer the related code?

I added a representation generation example for a skeleton sequence under in the `representation` subfolder. 

> 2. Could you tell me where the 'dfg' in train,py

I think you want to refer to cfg. We use hydra. The cfg is defined here:
```
@hydra.main(config_path="config/config.yaml")
def train_app(cfg):
    print(cfg.pretty())
```
and relies on the files that can be found in the `config` subfolder.

**Comment by RCpengnan** [comment]
> > 1.I am also confused how the skeleton is related to the image representation. Could you please offer the related code?
> 
> I added a representation generation example for a skeleton sequence under in the `representation` subfolder.
> 
> > 2. Could you tell me where the 'dfg' in train,py
> 
> I think you want to refer to cfg. We use hydra. The cfg is defined here:
> 
> ```
> @hydra.main(config_path="config/config.yaml")
> def train_app(cfg):
>     print(cfg.pretty())
> ```
> 
> and relies on the files that can be found in the `config` subfolder.
Thank you for your reply!
