### ISSUE TITLE
How to convert skeleton sequences into image representations?

### ISSUE THREAD

**Issue by charlietie** [raphaelmemmesheimer/skeleton-dml#6]
Hi:
Your work is very cool!

But I want to know how to **convert the raw skeleton sequence into image representations.** 
As there is no relevant code.
If possible, I want to use this approach on other skeleton datasets, e.g. kinetics skeleton.

Could you provide the detailed code! I will appreciate for your help!

Thanks!

**Comment by raphaelmemmesheimer** [comment]
Hey @charlietie,

example code for the image representation generation is here:

https://github.com/raphaelmemmesheimer/skeleton-dml/tree/main/representation

You slightly need to adapt it to the kinetics skeletons.

**Comment by charlietie** [comment]
Thanks! 
I will try to adapt it.

**Comment by guedesopaulo** [comment]
Hi, good job man. This conversion code of yours also applies to the NTU RGB+D 120 dataset? What I really wanted to know is how to get to the Precalculated Representations that you shared in this github.

**Comment by raphaelmemmesheimer** [comment]
Yes, the skeletons are very similar. The same code can be used for the NTU-120 dataset.
