### ISSUE TITLE
issue with config

### ISSUE THREAD

**Issue by mwmilad** [raphaelmemmesheimer/skeleton-dml#7]
Hi my friend, when i run !python train.py dataset=ntu
I get this error

INFO:root:pytorch-metric-learning VERSION 0.9.89
INFO:root:record_keeper VERSION 0.9.32
train.py:216: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="config/config.yaml")
Traceback (most recent call last):
  File "train.py", line 346, in <module>
    train_app()
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 335, in _run_hydra
    validate_config_path(config_path)
  File "/usr/local/lib/python3.8/dist-packages/hydra/core/utils.py", line 293, in validate_config_path
    raise ValueError(msg)
ValueError: Using config_path to specify the config name is not supported, specify the config name via config_name.
See https://hydra.cc/docs/1.2/upgrades/0.11_to_1.0/config_path_changes

**Comment by raphaelmemmesheimer** [comment]
You have to give dataset names corresponding to the filenames in the `config/dataset` folder. E.g.: 

```
python train.py dataset=ntu_reindex
```

**Comment by mwmilad** [comment]
**Tnx for your attention.**

I change my code but I get same error.

!git clone https://github.com/raphaelmemmesheimer/skeleton-dml
%cd skeleton-dml
!pip install -r requirements.txt
!export DATASET_FOLDER="$(pwd)/data"
!mkdir -p data/ntu/
!wget https://agas.uni-koblenz.de/skeleton-dml/skeleton-dml-ntu_120_one_shot.zip
!unzip skeleton-dml-ntu_120_one_shot.zip -d /content/skeleton-dml/data/ntu/ntu_reindex
!python train.py dataset=ntu_reindex

**Comment by raphaelmemmesheimer** [comment]
This most probably relates to a more recent hydra version.

Could you try to install hydra with: 
```
pip install hydra-core==0.11.3
```

and then retry.
