### ISSUE TITLE
Issue with evaluation

### ISSUE THREAD

**Issue by estefaniesiqueiracin** [raphaelmemmesheimer/skeleton-dml#8]
Hi, I'm a dev and I'm used to pytorch but I'm having trouble understanding how the training evaluation is being done and how the trainer(TrainWithClassifier) ​​influences the evaluation

**Comment by raphaelmemmesheimer** [comment]
The evaluation and testing is done using the OneShotTester which overwrites the BaseTester class from pytorch metric learning and executed after each epoch depending on the validation or test mode. The BaseTester call itself is nested in pytorch metric learning. Hope this helps.
